/* ============================================================
   i18n.js — bilingual ES / EN strings
   ============================================================ */
(function (TL) {
  const DICT = {
    es: {
      tagline: 'Pizarra táctica',
      hero_1: 'Dibuja.', hero_2: 'Anima.', hero_3: 'Gana.',
      hero_lead: 'Crea tácticas animadas sobre una pista real, divídelas en pasos y reprodúcelas como un entrenador profesional.',
      cta_create: 'Crear táctica animada',
      cta_match: 'Crear partido',
      cta_rivals: 'Mis rivales',
      q_match_d: 'Planifica un encuentro y asocia tus jugadas.',
      q_rivals_d: 'Fichas de rivales: golpes, debilidades y notas.',
      q_create_d: 'Pista interactiva con pasos y reproducción.',
      live_demo: 'Demo en vivo',
      sec_tactics: 'Últimas tácticas',
      sec_tactics_k: 'Tu biblioteca',
      sec_matches: 'Últimos partidos',
      sec_matches_k: 'Calendario',
      see_all: 'Ver todas',
      new_tactic: 'Nueva táctica',
      empty_tactics_h: 'Aún no hay tácticas',
      empty_tactics_p: 'Crea tu primera jugada animada y aparecerá aquí lista para reproducir y compartir.',
      empty_matches_h: 'Sin partidos todavía',
      empty_matches_p: 'Los partidos llegarán en la próxima fase. De momento, céntrate en tus tácticas.',
      coming_soon: 'Próximamente',
      // editor
      ed_kicker: 'Editor táctico',
      untitled: 'Táctica sin título',
      tool_select: 'Seleccionar / mover',
      tool_own: 'Añadir jugador propio',
      tool_rival: 'Añadir rival',
      tool_ball: 'Colocar la bola',
      tool_ballpath: 'Trayectoria de la bola',
      tool_ownmove: 'Movimiento propio',
      tool_rivalmove: 'Movimiento rival',
      tool_arrow: 'Flecha',
      tool_line: 'Línea',
      tool_point: 'Punto',
      tool_text: 'Texto',
      tool_zone: 'Zona / objetivo',
      tool_measure: 'Medir distancia',
      tool_erase: 'Borrar elemento',
      reverse: 'Inversa', reverse_d: 'Reproducir la jugada al revés',
      zone_hint: 'Arrastra para marcar una zona en la pista',
      measure_hint: 'Arrastra para medir la distancia',
      view_full: 'Pista completa',
      view_half: 'Media pista',
      surf_clay: 'Tierra',
      surf_hard: 'Rápida',
      surf_grass: 'Hierba',
      surf_indoor: 'Indoor',
      steps: 'Pasos de la jugada',
      add_step: 'Añadir paso',
      del_step: 'Eliminar paso',
      prev_step: 'Paso anterior',
      next_step: 'Paso siguiente',
      play: 'Reproducir jugada',
      pause: 'Pausa',
      restart: 'Reiniciar',
      speed: 'Velocidad',
      slow: 'Lento', normal: 'Normal', fast: 'Rápido',
      insp_props: 'Propiedades del trazo',
      insp_color: 'Color',
      insp_line: 'Tipo de línea',
      solid: 'Sólida', dash: 'Discontinua',
      legend: 'Leyenda',
      lg_own: 'Tú', lg_rival: 'Rival', lg_ball: 'Bola',
      lg_ownmove: 'Mov. propio', lg_rivalmove: 'Mov. rival', lg_ballpath: 'Tray. bola',
      play_dna: 'ADN de la jugada', dna_shots: 'golpes',
      save: 'Guardar',
      share: 'Compartir',
      back: 'Inicio',
      clear_step: 'Vaciar paso',
      // save modal
      save_title: 'Guardar táctica',
      f_name: 'Nombre',
      f_desc: 'Descripción',
      f_surface: 'Superficie',
      f_playtype: 'Tipo de jugada',
      pt_serve: 'Saque', pt_return: 'Resto', pt_defense: 'Defensa', pt_attack: 'Ataque', pt_net: 'Subida a red',
      cancel: 'Cancelar',
      save_confirm: 'Guardar táctica',
      // share modal
      share_title: 'Compartir táctica',
      share_link: 'Enlace privado (solo lectura)',
      copy: 'Copiar',
      copied: 'Enlace copiado',
      sh_img: 'Exportar como imagen',
      sh_img_d: 'Descarga un PNG de la jugada.',
      sh_brand: 'Tarjeta para compartir',
      sh_brand_d: 'Imagen vertical con tu marca, lista para redes.',
      sh_pdf: 'Exportar como PDF',
      sh_pdf_d: 'Hoja táctica imprimible.',
      sh_video: 'Exportar vídeo (WebM)',
      sh_video_d: 'Anima la secuencia completa.',
      sh_gif: 'Exportar GIF',
      sh_gif_d: 'GIF animado para WhatsApp.',
      gif_building: 'Creando GIF…',
      sh_wa: 'Enviar por WhatsApp',
      sh_wa_d: 'Comparte el enlace al instante.',
      sh_mail: 'Enviar por correo',
      sh_mail_d: 'Adjunta el enlace de la jugada.',
      saved_ok: 'Táctica guardada',
      step_added: 'Paso añadido',
      img_exported: 'Imagen exportada',
      vid_building: 'Generando vídeo…', vid_done: 'Vídeo exportado', vid_need: 'Añade al menos un golpe para animar', vid_unsupported: 'Tu navegador no permite exportar vídeo aquí',
      open: 'Abrir', edit: 'Editar', duplicate: 'Duplicar', delete: 'Eliminar', del_confirm: '¿Eliminar esta táctica?',
      hint_draw: 'Arrastra sobre la pista para dibujar',
      hint_place: 'Toca la pista para colocar',
      hint_text: 'Toca la pista para escribir',
      hint_select: 'Arrastra las fichas para moverlas',
      text_prompt: 'Texto de la anotación:',
      viewer_mode: 'Modo visor — solo lectura',
      surfaces: 'Superficie', playtypes: 'Tipo de jugada', all: 'Todas',
      guided_kicker: 'Modo guiado',
      g_start: 'Inicio',
      g_serve: 'Saque', g_return: 'Resto', g_shot: 'Golpe',
      g_you_serve: 'Sacas tú', g_rival_return: 'Resta el rival',
      g_rival_serve: 'Saca el rival', g_you_return: 'Restas tú',
      g_you_hit: 'Golpeas tú', g_rival_hit: 'Golpea el rival',
      g_hint_serve: 'Toca la pista donde quieres que bote tu saque',
      g_hint_rserve: 'Toca dónde saca el rival',
      g_hint_return: 'Toca a dónde devuelve el rival',
      g_hint_yreturn: 'Toca a dónde restas tú',
      g_hint_you: 'Toca a dónde colocas tu siguiente golpe',
      g_hint_rival: 'Toca a dónde la manda el rival',
      i_serve: 'Saco yo', rival_serves: 'Saca el rival', who_serves: '¿Quién saca?', who_hits: '¿Quién golpea?',
      g_undo: 'Deshacer', g_watch: 'Ver jugada', g_finish: 'Terminar y guardar',
      g_advanced: 'Modo avanzado', advanced_on: 'Modo avanzado activado',
      turn_you: 'Tu turno', turn_rival: 'Turno del rival',
      shot_how: '¿Cómo la pegas?',
      shot_plana: 'Plana', shot_lift: 'Liftada', shot_cortado: 'Cortado', shot_globo: 'Globo', shot_dejada: 'Dejada',
      folders: 'Carpetas', all_tactics: 'Todas', new_folder: 'Nueva carpeta',
      new_folder_prompt: 'Nombre de la nueva carpeta:', rename_folder_prompt: 'Nuevo nombre de la carpeta:',
      del_folder: '¿Eliminar esta carpeta? Las tácticas no se borran, quedan sin carpeta.',
      rename: 'Renombrar', f_folder: 'Carpeta', no_folder: 'Sin carpeta', f_number: 'Número',
      move_to: 'Mover a…', folder_created: 'Carpeta creada', no_tactics_folder: 'Esta carpeta aún no tiene tácticas.',
      // rivals
      rivals_title: 'Mis rivales', rivals_k: 'Scouting', new_rival: 'Nuevo rival', edit_rival: 'Editar rival',
      empty_rivals_h: 'Aún no hay rivales', empty_rivals_p: 'Crea la ficha de un rival con sus golpes y debilidades para preparar tus tácticas.',
      r_name: 'Nombre', r_hand: 'Mano dominante', r_right: 'Diestro', r_left: 'Zurdo',
      r_best: 'Mejor golpe', r_weak: 'Punto débil', r_style: 'Estilo de juego', r_notes: 'Notas tácticas',
      r_style_ph: 'Ej. agresivo de fondo, contraataque…', r_best_ph: 'Ej. derecha cruzada', r_weak_ph: 'Ej. revés alto',
      del_rival: '¿Eliminar este rival? También se borran sus partidos.', save_rival: 'Guardar rival',
      linked_tactics: 'tácticas', view_tactics: 'Ver tácticas', no_rival: 'Sin rival', f_rival: 'Rival',
      rival_saved: 'Rival guardado',
      // matches
      matches_title: 'Partidos', new_match: 'Nuevo partido', edit_match: 'Editar partido',
      empty_matches_h2: 'Sin partidos todavía', empty_matches_p2: 'Crea un partido, asóciale tácticas y registra después el resultado y el análisis.',
      m_rival: 'Rival', m_date: 'Fecha', m_surface: 'Superficie', m_goal: 'Objetivo táctico', m_goal_ph: 'Ej. presionar con el saque y subir',
      m_tactics: 'Tácticas del partido', m_played: 'Partido jugado', m_result: 'Resultado', m_result_ph: 'Ej. 6-4, 3-6, 7-5',
      m_worked: 'Qué táctica funcionó', m_failed: 'Qué táctica no funcionó', m_train: 'Qué debo entrenar', m_rating: 'Valoración',
      save_match: 'Guardar partido', del_match: '¿Eliminar este partido?', match_saved: 'Partido guardado',
      upcoming: 'Próximo', played: 'Jugado', pick_tactics: 'Elige las tácticas a usar', no_tactics_yet: 'Crea tácticas primero para asociarlas.',
      register_result: 'Registrar resultado', match_analysis: 'Resultado y análisis',
      // match prep + auto plan
      prep: 'Preparar', prep_title: 'Preparación del partido', prep_plan: 'Plan de juego sugerido',
      prep_weak: 'Aprovecha su punto débil', prep_tactics: 'Tácticas para este partido', prep_goal: 'Tu objetivo',
      prep_no_rival: 'Asocia un rival al partido para ver su scouting y el plan.',
      prep_no_plan: 'Añade el punto débil y el estilo del rival en su ficha para generar un plan.',
      prep_no_tactics: 'Sin tácticas asociadas. Edita el partido para añadirlas.',
      prep_scout: 'Scouting del rival', prep_print: 'Imprimir', prep_open: 'Ver',
      m_outcome: 'Resultado', won: 'Ganado', lost: 'Perdido',
      // match details
      m_location: 'Localización / club', m_location_ph: 'Ej. Club de Tenis Valencia',
      m_tournament: 'Torneo / competición', m_tournament_ph: 'Ej. Liga provincial', m_round: 'Ronda', round_ph: 'Ej. Cuartos',
      m_type: 'Tipo de partido', mt_official: 'Oficial', mt_friendly: 'Amistoso', mt_practice: 'Entreno',
      m_duration: 'Duración', m_duration_ph: 'Ej. 1h 45m', m_conditions: 'Condiciones',
      cond_sun: 'Sol', cond_wind: 'Viento', cond_indoor: 'Indoor', cond_heat: 'Calor', cond_cold: 'Frío', cond_night: 'Nocturno', cond_rain: 'Lluvia',
      m_sets: 'Marcador por sets', set_add: 'Añadir set', m_details: 'Detalles del partido',
      // stats unlocked
      stat_by_club: 'Por club', stat_by_tour: 'Por torneo', best_court: 'Tu mejor pista', worst_court: 'Tu peor pista',
      win_history: 'Historial', loc_unknown: 'Sin localización',
      // rival ranking + photo
      r_rank: 'Ranking / nº RFET', r_rank_ph: 'Ej. #1240 RFET', r_cat: 'Categoría', r_cat_ph: 'Ej. Absoluto, Sub-16, 3ª',
      r_photo: 'Foto', search_rfet: 'Buscar en la RFET', rfet_hint: 'Abre la web de la RFET con el nombre. Copia el ranking y pégalo aquí.', add_photo: 'Subir foto', remove_photo: 'Quitar foto',
      rival_detail: 'Ficha del rival', stat_played: 'Partidos', stat_winrate: '% ganados', stat_best: 'Táctica top',
      rival_matches: 'Partidos contra él', no_matches_rival: 'Aún no hay partidos contra este rival.', dash: '—',
      // dashboard
      dash_kicker: 'Resumen', dash_tactics: 'Tácticas', dash_rivals: 'Rivales', dash_matches: 'Partidos', dash_winrate: '% ganados',
      // search + sort
      search_ph: 'Buscar tácticas…', sort_recent: 'Recientes', sort_name: 'Nombre', sort_steps: 'Más golpes', no_results: 'Sin resultados para tu búsqueda.',
      // templates
      tpl_title: 'Empieza tu táctica', tpl_sub: 'Elige un punto de partida o crea desde cero.',
      tpl_blank: 'Pista en blanco', tpl_blank_d: 'Tú decides cada golpe paso a paso.',
      sport_tennis: 'Tenis', sport_padel: 'Pádel', sport_pickle: 'Pickleball', sport: 'Deporte',
      r_weakside: '¿A quién atacar?', ws_left: 'Izq. (R1)', ws_even: 'Iguales', ws_right: 'Der. (R2)',
      r_pairname: 'Nombre de la pareja', r_pname: 'Nombre', r_pbest: 'Su arma', r_pweak: 'Su débil',
      tpl_blank_padel: 'Pista de pádel', tpl_blank_padel_d: '2 vs 2 con paredes. Coloca y dibuja la jugada.',
      tpl_blank_pickle: 'Pista de pickleball', tpl_blank_pickle_d: '2 vs 2 con cocina. Coloca y dibuja la jugada.',
      tpl_p_saque: 'Saque y subida', tpl_p_saque_d: 'Saca y toma la red para definir de volea.',
      tpl_p_bandeja: 'Bandeja', tpl_p_bandeja_d: 'Responde el globo con bandeja y mantén la red.',
      tpl_p_globo: 'Globo y ataque', tpl_p_globo_d: 'Globo profundo, sube a la red y remata.',
      tpl_serve_volley: 'Saque y volea', tpl_serve_volley_d: 'Saque abierto + subida a definir en la red.',
      tpl_return: 'Resto agresivo', tpl_return_d: 'Devolución profunda y toma del control.',
      tpl_baseline: 'Peloteo de fondo', tpl_baseline_d: 'Intercambio cruzado y cambio de dirección.',
      tpl_drop: 'Dejada y passing', tpl_drop_d: 'Dejada para subir al rival y passing.',
      tpl_counter: 'Contraataque', tpl_counter_d: 'Defiende profundo y gira a ataque.',
      tpl_defense: 'Defensa y globo', tpl_defense_d: 'Resta defensiva y globo para recolocarte.',
      use_template: 'Usar plantilla',
      // onboarding
      ob_title: 'Bienvenido a CourtLab', ob_sub: 'Tu pizarra táctica de tenis en 3 pasos.',
      ob_1_t: 'Dibuja el punto', ob_1_d: 'En modo guiado, la app te pide cada golpe. Solo tocas dónde va la bola.',
      ob_2_t: 'Anima la jugada', ob_2_d: 'Dale a reproducir y mira la jugada con movimiento realista.',
      ob_3_t: 'Guarda y comparte', ob_3_d: 'Organiza en carpetas, asocia rivales y exporta a imagen, PDF o vídeo.',
      ob_start: 'Crear mi primera táctica', ob_skip: 'Explorar por mi cuenta',
      // editor extras
      duplicate_step: 'Duplicar paso', tactic_duplicated: 'Táctica duplicada', dup_tactic: 'Duplicar táctica',
      shortcuts: 'Atajos de teclado', sc_play: 'Reproducir / pausar', sc_steps: 'Paso anterior / siguiente',
      sc_undo: 'Deshacer último golpe', sc_back: 'Volver al inicio', sc_save: 'Guardar', kb_hint: 'Pulsa ? para ver los atajos',
      // tags
      f_tag: 'Etiqueta', tag_off: 'Sin etiqueta', tags_label: 'Etiquetas', filter_tag: 'Etiqueta',
      tag_serve: 'Saque', tag_return: 'Resto', tag_defense: 'Defensa', tag_attack: 'Ataque', tag_special: 'Especial',
      // score situation
      f_score: 'Situación de marcador', score_any: 'Cualquiera', score_break: 'Bola de break', score_set: 'Set point',
      score_match: 'Match point', score_deuce: 'Iguales (deuce)', score_pressure: 'Bajo presión',
      // notes per shot
      step_note: 'Nota del golpe', note_ph: 'Ej. abre con efecto al revés', notes_short: 'Nota',
      // mirror
      mirror: 'Voltear', flipped: 'Jugada volteada', mirror_d: 'Cambiar de lado (iguales ↔ ventaja)',
      // doubles
      doubles: 'Dobles', singles: 'Individual', mode_play: 'Modalidad', partner_you: 'Compañero', partner_rival: 'Rival 2',
      // stats by surface / tactic
      stat_by_surface: 'Por superficie', stat_by_tactic: 'Tácticas que funcionan', stat_uses: 'usos', stat_record: 'balance',
      stat_no_data: 'Juega partidos para ver estadísticas.', stat_success: 'éxito',
      // progress
      progress: 'Progreso', progress_k: 'Últimos partidos', win_label: 'V', loss_label: 'D',
      // compare rivals
      compare: 'Comparar', compare_title: 'Comparar rivales', pick_two: 'Elige dos rivales para comparar.', vs: 'vs',
      // playbook
      playbook: 'Playbook PDF', playbook_d: 'Reúne varias tácticas en un documento imprimible.',
      proplays: 'Jugadas Pro', proplays_d: 'Jugadas listas de nivel profesional, gratis y premium.',
      playbook_title: 'Crear Playbook', pick_for_playbook: 'Elige las tácticas a incluir', export_playbook: 'Generar Playbook', playbook_empty: 'Selecciona al menos una táctica.',
      // sound + logo
      s_sound: 'Sonido al golpear', s_haptic: 'Vibración', s_haptic_d: 'Respuesta táctil al guardar, completar y navegar.', s_logo: 'Logo del club', s_logo_d: 'Aparecerá en imágenes y PDF exportados.',
      s_motion: 'Reducir animaciones', s_motion_d: 'Menos movimiento en toda la app. Por defecto sigue los ajustes de tu sistema.',
      logo_added: 'Logo añadido', remove_logo: 'Quitar logo', add_logo: 'Subir logo',
      settings: 'Ajustes', s_theme: 'Tema', theme_dark: 'Oscuro', theme_light: 'Claro', s_accent: 'Color de acento',
      s_account: 'Cuenta', s_premium: 'Premium', go_premium: 'Hazte Premium', premium_on: 'Premium activo', s_admin: 'Código admin', admin_ph: 'Código de administrador', admin_ok: 'Cuenta admin activada', admin_bad: 'Código no válido', admin_active: 'Admin · Premium gratis',
      s_about: 'Acerca de', s_version: 'Versión', s_reset_tutorial: 'Ver tutorial otra vez', s_reset_tutorial_d: 'Vuelve a mostrar la guía de bienvenida', tutorial_reset: 'Tutorial reactivado · vuelve al inicio', s_update: 'Buscar actualizaciones', s_update_d: 'Recarga la última versión de la app', updating: 'Actualizando…',
      s_support: 'Soporte', s_contact: 'Contacto', s_feedback: 'Enviar sugerencia', feedback_ph: 'Cuéntanos qué mejorarías…', feedback_sent: '¡Gracias por tu sugerencia!', s_privacy: 'Privacidad', s_terms: 'Términos', s_about: 'Acerca de',
      cloud_off: 'Nube no disponible sin conexión', sign_in: 'Iniciar sesión', sign_up: 'Crear cuenta', create_account: 'Crear cuenta', sign_out: 'Cerrar sesión', signed_out: 'Sesión cerrada', synced_ok: 'Datos sincronizados', need_account: 'Crear cuenta nueva', have_account: 'Ya tengo cuenta', email: 'Email', password: 'Contraseña', logged_as: 'Sesión iniciada', cloud_sync: 'Sincronizado en la nube', forgot_pass: '¿Olvidaste tu contraseña?', reset_title: 'Recuperar contraseña', reset_send: 'Enviar enlace', reset_sent: 'Te hemos enviado un correo para restablecer la contraseña.', reset_email_first: 'Escribe tu email primero.', new_pass: 'Nueva contraseña', save_pass: 'Guardar contraseña', pass_updated: 'Contraseña actualizada · sesión iniciada', share_public: 'Crear enlace público', share_public_d: 'Cualquiera con el enlace puede verla', share_need_login: 'Inicia sesión para crear un enlace público', publishing: 'Publicando…', link_public: 'Enlace público', share_ready: '¡Enlace público listo!', share_not_found: 'Enlace no encontrado o caducado',
      tactic_limit_hit: 'Has llegado al límite gratis · hazte Premium para tácticas ilimitadas',
      ref_welcome_toast: 'Te invitó un amigo · ¡7 días de Premium gratis! 🎁',
      ref_welcome_sub: 'Cada amigo que entre con tu enlace recibe 7 días de Premium de regalo',
      install_app: 'Instalar app', install_d: 'Añádela a tu pantalla de inicio', install_done: '¡App instalada! 🎾',
      trial_remind5: 'Te quedan 2 días de prueba Premium · cancela cuando quieras', trial_remind_last: 'Último día de prueba Premium · ¿la conservas?',
      streak_days: 'días seguidos', streak_day1: 'día', streak_today: '¡hoy en racha!', streak_label: 'Racha',
      notify_match: 'Partido pronto', notify_match_body: 'prepara tu plan en CourtLab', notify_remind: 'Avísame', notify_on: 'Te avisaremos antes del partido 🔔', notify_blocked: 'Activa las notificaciones en tu navegador',
      save_label: 'Ahorra', per_month_eq: '/mes',
      s_club: 'Modo Club', club_title: 'Club', club_open: 'Abrir Club', club_d: 'Comparte tácticas con tu equipo',
      club_create: 'Crear club', club_join: 'Unirse a un club', club_name_ph: 'Nombre del club', club_code_ph: 'Código de invitación',
      club_code: 'Código', club_created: 'Club creado', club_joined: 'Te has unido al club', club_not_found: 'Código no válido',
      club_role_coach: 'Entrenador', club_role_player: 'Jugador', club_shared: 'Tácticas del club', club_share_tactic: 'Compartir táctica',
      club_players: 'Jugadores', club_leave: 'Salir del club', club_leave_confirm: '¿Seguro que quieres salir del club?', club_left: 'Has salido del club',
      club_no_tactics: 'Aún no hay tácticas compartidas.', club_import: 'Añadir a las mías', club_imported: 'Añadida a tu biblioteca',
      club_shared_ok: 'Táctica compartida con el club', club_need_login: 'Inicia sesión para usar el Modo Club',
      nav_home: 'Inicio', nav_tactics: 'Tácticas', nav_rivals: 'Rivales', nav_matches: 'Partidos', nav_profile: 'Perfil',
      dash_hi: 'Tu pizarra táctica', dash_recent: 'Últimas tácticas', see_all_t: 'Ver todas', quick_actions: 'Acciones rápidas',
      fav: 'Favorita', favs_only: 'Favoritas', view_toggle: 'Vista lista / cuadrícula', fav_added: 'Añadida a favoritas', fav_removed: 'Quitada de favoritas', all: 'Todos', r_partner: 'Pareja (pádel)', r_partner_ph: 'Compañero/a del rival',
      rank_title: 'Tu rango', rank_next: 'para subir a', rank_max: '¡Rango máximo!', rank_xp: 'XP', r_debut: 'Debutante', r_pelot: 'Peloteador', r_estr: 'Estratega', r_maestro: 'Maestro de Pista', r_crack: 'Crack', r_leyenda: 'Leyenda',
      ach_first_tactic:'Primer golpe', ach_first_tactic_d:'Crea tu primera táctica',
      ach_five_tactics:'Estratega', ach_five_tactics_d:'Guarda 5 tácticas',
      ach_first_padel:'Bienvenido al pádel', ach_first_padel_d:'Crea tu primera táctica de pádel',
      ach_first_match:'A competir', ach_first_match_d:'Registra tu primer partido',
      ach_ten_matches:'Veterano', ach_ten_matches_d:'Registra 10 partidos',
      ach_five_wins:'Ganador', ach_five_wins_d:'Consigue 5 victorias',
      ach_three_rivals:'Cazador', ach_three_rivals_d:'Añade 3 rivales',
      ach_streak3:'En racha', ach_streak3_d:'Úsala 3 días seguidos',
      ach_streak7:'Imparable', ach_streak7_d:'Úsala 7 días seguidos',
      ach_share5:'Embajador', ach_share5_d:'Comparte 5 tácticas',
      ach_invite10:'Mentor', ach_invite10_d:'Invita a 10 amigos',
      rematch: 'Revancha', rematch_done: 'Revancha creada', present: 'Presentar', present_mode: 'Modo presentación',
      export_scout_pdf: 'Informe en PDF', scout_report: 'Informe de scouting',
      // calendar / diary / goals
      qr_cal_s: 'Próximos partidos', qr_goal_s: 'Metas de temporada', qr_diary_s: 'Notas y sensaciones',
      calendar: 'Calendario', cal_upcoming: 'Próximos partidos', cal_this_week: 'Esta semana', cal_later: 'Más adelante', cal_past: 'Jugados', cal_empty: 'No hay partidos programados.',
      diary: 'Diario', diary_k: 'Entrenamiento', new_entry: 'Nueva entrada', edit_entry: 'Editar entrada', diary_empty_h: 'Tu diario está vacío', diary_empty_p: 'Anota qué entrenaste y cómo te sentiste, día a día.',
      d_date: 'Fecha', d_focus: 'Qué entrené', d_focus_ph: 'Ej. saque y subida, derecha cruzada', d_notes: 'Sensaciones / notas', d_notes_ph: 'Cómo te sentiste, qué mejorar…', d_mood: 'Sensación', d_dur: 'Duración', save_entry: 'Guardar entrada', del_entry: '¿Eliminar esta entrada?', entry_saved: 'Entrada guardada',
      mood_bad: 'Floja', mood_ok: 'Normal', mood_good: 'Buena', mood_great: 'Excelente',
      goals: 'Objetivos', goals_k: 'Temporada', new_goal: 'Nuevo objetivo', edit_goal: 'Editar objetivo', goals_empty_h: 'Sin objetivos aún', goals_empty_p: 'Fíjate metas de temporada y sigue tu progreso automáticamente.',
      g_title: 'Objetivo', g_title_ph: 'Ej. Ganar el 70% en tierra', g_type: 'Tipo', g_surface: 'Superficie', g_any_surface: 'Todas', g_target: 'Meta',
      gt_winrate: '% de victorias', gt_wins: 'Nº de victorias', gt_matches: 'Partidos jugados', gt_manual: 'Manual (yo lo actualizo)', g_current: 'Progreso actual', save_goal: 'Guardar objetivo', del_goal: '¿Eliminar este objetivo?', goal_saved: 'Objetivo guardado', goal_done: '¡Conseguido!',
      s_lang: 'Idioma', s_data: 'Tus datos',
      s_export: 'Descargar copia de seguridad', s_export_d: 'Tácticas, carpetas, rivales y partidos en un archivo.',
      s_import: 'Restaurar copia', s_import_d: 'Carga un archivo de copia anterior.',
      s_wipe: 'Borrar todos los datos', s_wipe_confirm: '¿Seguro? Se borrarán tácticas, carpetas, rivales y partidos de este navegador.',
      data_exported: 'Copia descargada', data_imported: 'Copia restaurada', import_bad: 'Archivo no válido',
      step_names: ['Saque abierto','Resto cruzado','Derecha al revés','Subida a red','Cierre del punto'],
    },
    en: {
      tagline: 'Tactics board',
      hero_1: 'Draw.', hero_2: 'Animate.', hero_3: 'Win.',
      hero_lead: 'Build animated tactics on a real court, break them into steps and play them back like a pro coach.',
      cta_create: 'Create animated tactic',
      cta_match: 'Create match',
      cta_rivals: 'My rivals',
      q_match_d: 'Plan a match and link your plays.',
      q_rivals_d: 'Rival profiles: strokes, weaknesses, notes.',
      q_create_d: 'Interactive court with steps and playback.',
      live_demo: 'Live demo',
      sec_tactics: 'Latest tactics',
      sec_tactics_k: 'Your library',
      sec_matches: 'Latest matches',
      sec_matches_k: 'Schedule',
      see_all: 'See all',
      new_tactic: 'New tactic',
      empty_tactics_h: 'No tactics yet',
      empty_tactics_p: 'Create your first animated play and it will show up here, ready to replay and share.',
      empty_matches_h: 'No matches yet',
      empty_matches_p: 'Matches arrive in the next phase. For now, focus on your tactics.',
      coming_soon: 'Coming soon',
      ed_kicker: 'Tactic editor',
      untitled: 'Untitled tactic',
      tool_select: 'Select / move',
      tool_own: 'Add own player',
      tool_rival: 'Add rival',
      tool_ball: 'Place the ball',
      tool_ballpath: 'Ball trajectory',
      tool_ownmove: 'Own movement',
      tool_rivalmove: 'Rival movement',
      tool_arrow: 'Arrow',
      tool_line: 'Line',
      tool_point: 'Point',
      tool_text: 'Text',
      tool_zone: 'Zone / target',
      tool_measure: 'Measure distance',
      tool_erase: 'Erase element',
      reverse: 'Reverse', reverse_d: 'Play the point backwards',
      zone_hint: 'Drag to mark a zone on the court',
      measure_hint: 'Drag to measure distance',
      view_full: 'Full court',
      view_half: 'Half court',
      surf_clay: 'Clay',
      surf_hard: 'Hard',
      surf_grass: 'Grass',
      surf_indoor: 'Indoor',
      steps: 'Play steps',
      add_step: 'Add step',
      del_step: 'Delete step',
      prev_step: 'Previous step',
      next_step: 'Next step',
      play: 'Play tactic',
      pause: 'Pause',
      restart: 'Restart',
      speed: 'Speed',
      slow: 'Slow', normal: 'Normal', fast: 'Fast',
      insp_props: 'Stroke properties',
      insp_color: 'Color',
      insp_line: 'Line type',
      solid: 'Solid', dash: 'Dashed',
      legend: 'Legend',
      lg_own: 'You', lg_rival: 'Rival', lg_ball: 'Ball',
      lg_ownmove: 'Own move', lg_rivalmove: 'Rival move', lg_ballpath: 'Ball path',
      play_dna: 'Play DNA', dna_shots: 'shots',
      save: 'Save',
      share: 'Share',
      back: 'Home',
      clear_step: 'Clear step',
      save_title: 'Save tactic',
      f_name: 'Name',
      f_desc: 'Description',
      f_surface: 'Surface',
      f_playtype: 'Play type',
      pt_serve: 'Serve', pt_return: 'Return', pt_defense: 'Defense', pt_attack: 'Attack', pt_net: 'Net rush',
      cancel: 'Cancel',
      save_confirm: 'Save tactic',
      share_title: 'Share tactic',
      share_link: 'Private link (read-only)',
      copy: 'Copy',
      copied: 'Link copied',
      sh_img: 'Export as image',
      sh_img_d: 'Download a PNG of the play.',
      sh_brand: 'Shareable card',
      sh_brand_d: 'Branded portrait image, ready for social.',
      sh_pdf: 'Export as PDF',
      sh_pdf_d: 'Printable tactic sheet.',
      sh_video: 'Export video (WebM)',
      sh_video_d: 'Animate the full sequence.',
      sh_gif: 'Export GIF',
      sh_gif_d: 'Animated GIF for WhatsApp.',
      gif_building: 'Building GIF…',
      sh_wa: 'Send via WhatsApp',
      sh_wa_d: 'Share the link instantly.',
      sh_mail: 'Send via email',
      sh_mail_d: 'Attach the play link.',
      saved_ok: 'Tactic saved',
      step_added: 'Step added',
      img_exported: 'Image exported',
      vid_building: 'Building video…', vid_done: 'Video exported', vid_need: 'Add at least one shot to animate', vid_unsupported: 'Your browser can\'t export video here',
      open: 'Open', edit: 'Edit', duplicate: 'Duplicate', delete: 'Delete', del_confirm: 'Delete this tactic?',
      hint_draw: 'Drag on the court to draw',
      hint_place: 'Tap the court to place',
      hint_text: 'Tap the court to add text',
      hint_select: 'Drag the tokens to move them',
      text_prompt: 'Annotation text:',
      viewer_mode: 'Viewer mode — read only',
      surfaces: 'Surface', playtypes: 'Play type', all: 'All',
      guided_kicker: 'Guided mode',
      g_start: 'Start',
      g_serve: 'Serve', g_return: 'Return', g_shot: 'Shot',
      g_you_serve: 'You serve', g_rival_return: 'Rival returns',
      g_rival_serve: 'Rival serves', g_you_return: 'You return',
      g_you_hit: 'You hit', g_rival_hit: 'Rival hits',
      g_hint_serve: 'Tap where you want your serve to land',
      g_hint_rserve: 'Tap where the rival serves',
      g_hint_return: 'Tap where the rival returns it',
      g_hint_yreturn: 'Tap where you return it',
      g_hint_you: 'Tap where you place your next shot',
      g_hint_rival: 'Tap where the rival sends it',
      i_serve: 'I serve', rival_serves: 'Rival serves', who_serves: 'Who serves?', who_hits: 'Who hits?',
      g_undo: 'Undo', g_watch: 'Watch play', g_finish: 'Finish & save',
      g_advanced: 'Advanced mode', advanced_on: 'Advanced mode on',
      turn_you: 'Your turn', turn_rival: 'Rival turn',
      shot_how: 'How do you hit it?',
      shot_plana: 'Flat', shot_lift: 'Topspin', shot_cortado: 'Slice', shot_globo: 'Lob', shot_dejada: 'Drop',
      folders: 'Folders', all_tactics: 'All', new_folder: 'New folder',
      new_folder_prompt: 'New folder name:', rename_folder_prompt: 'New folder name:',
      del_folder: 'Delete this folder? Tactics are not removed, they become unfiled.',
      rename: 'Rename', f_folder: 'Folder', no_folder: 'No folder', f_number: 'Number',
      move_to: 'Move to…', folder_created: 'Folder created', no_tactics_folder: 'This folder has no tactics yet.',
      // rivals
      rivals_title: 'My rivals', rivals_k: 'Scouting', new_rival: 'New rival', edit_rival: 'Edit rival',
      empty_rivals_h: 'No rivals yet', empty_rivals_p: 'Create a rival profile with their strokes and weaknesses to prepare your tactics.',
      r_name: 'Name', r_hand: 'Dominant hand', r_right: 'Right-handed', r_left: 'Left-handed',
      r_best: 'Best shot', r_weak: 'Weak spot', r_style: 'Playing style', r_notes: 'Tactical notes',
      r_style_ph: 'e.g. aggressive baseliner, counterpuncher…', r_best_ph: 'e.g. cross-court forehand', r_weak_ph: 'e.g. high backhand',
      del_rival: 'Delete this rival? Their matches are removed too.', save_rival: 'Save rival',
      linked_tactics: 'tactics', view_tactics: 'View tactics', no_rival: 'No rival', f_rival: 'Rival',
      rival_saved: 'Rival saved',
      // matches
      matches_title: 'Matches', new_match: 'New match', edit_match: 'Edit match',
      empty_matches_h2: 'No matches yet', empty_matches_p2: 'Create a match, link tactics and log the result and analysis afterwards.',
      m_rival: 'Rival', m_date: 'Date', m_surface: 'Surface', m_goal: 'Tactical goal', m_goal_ph: 'e.g. press with the serve and rush the net',
      m_tactics: 'Match tactics', m_played: 'Match played', m_result: 'Score', m_result_ph: 'e.g. 6-4, 3-6, 7-5',
      m_worked: 'What worked', m_failed: "What didn't work", m_train: 'What to train', m_rating: 'Rating',
      save_match: 'Save match', del_match: 'Delete this match?', match_saved: 'Match saved',
      upcoming: 'Upcoming', played: 'Played', pick_tactics: 'Pick the tactics to use', no_tactics_yet: 'Create tactics first to link them.',
      register_result: 'Log result', match_analysis: 'Result & analysis',
      // match prep + auto plan
      prep: 'Prepare', prep_title: 'Match preparation', prep_plan: 'Suggested game plan',
      prep_weak: 'Target their weakness', prep_tactics: 'Tactics for this match', prep_goal: 'Your goal',
      prep_no_rival: 'Link a rival to the match to see scouting and the plan.',
      prep_no_plan: 'Add the rival weak spot and style in their profile to generate a plan.',
      prep_no_tactics: 'No linked tactics. Edit the match to add them.',
      prep_scout: 'Rival scouting', prep_print: 'Print', prep_open: 'Open',
      m_outcome: 'Outcome', won: 'Won', lost: 'Lost',
      // match details
      m_location: 'Location / club', m_location_ph: 'e.g. Valencia Tennis Club',
      m_tournament: 'Tournament', m_tournament_ph: 'e.g. Regional league', m_round: 'Round', round_ph: 'e.g. Quarterfinal',
      m_type: 'Match type', mt_official: 'Official', mt_friendly: 'Friendly', mt_practice: 'Practice',
      m_duration: 'Duration', m_duration_ph: 'e.g. 1h 45m', m_conditions: 'Conditions',
      cond_sun: 'Sun', cond_wind: 'Wind', cond_indoor: 'Indoor', cond_heat: 'Heat', cond_cold: 'Cold', cond_night: 'Night', cond_rain: 'Rain',
      m_sets: 'Set scores', set_add: 'Add set', m_details: 'Match details',
      // stats unlocked
      stat_by_club: 'By club', stat_by_tour: 'By tournament', best_court: 'Your best surface', worst_court: 'Your worst surface',
      win_history: 'History', loc_unknown: 'No location',
      // rival ranking + photo
      r_rank: 'Ranking / RFET no.', r_rank_ph: 'e.g. #1240 RFET', r_cat: 'Category', r_cat_ph: 'e.g. Open, U16, 3rd',
      r_photo: 'Photo', search_rfet: 'Search on RFET', rfet_hint: 'Opens the RFET site with the name. Copy the ranking and paste it here.', add_photo: 'Upload photo', remove_photo: 'Remove photo',
      rival_detail: 'Rival profile', stat_played: 'Matches', stat_winrate: 'Win %', stat_best: 'Top tactic',
      rival_matches: 'Matches vs them', no_matches_rival: 'No matches against this rival yet.', dash: '—',
      // dashboard
      dash_kicker: 'Overview', dash_tactics: 'Tactics', dash_rivals: 'Rivals', dash_matches: 'Matches', dash_winrate: 'Win %',
      // search + sort
      search_ph: 'Search tactics…', sort_recent: 'Recent', sort_name: 'Name', sort_steps: 'Most shots', no_results: 'No results for your search.',
      // templates
      tpl_title: 'Start your tactic', tpl_sub: 'Pick a starting point or build from scratch.',
      tpl_blank: 'Blank court', tpl_blank_d: 'You decide every shot, step by step.',
      sport_tennis: 'Tennis', sport_padel: 'Padel', sport_pickle: 'Pickleball', sport: 'Sport',
      r_weakside: 'Who to attack?', ws_left: 'Left (R1)', ws_even: 'Even', ws_right: 'Right (R2)',
      r_pairname: 'Pair name', r_pname: 'Name', r_pbest: 'Strength', r_pweak: 'Weakness',
      tpl_blank_padel: 'Padel court', tpl_blank_padel_d: '2 vs 2 with walls. Place and draw the play.',
      tpl_blank_pickle: 'Pickleball court', tpl_blank_pickle_d: '2 vs 2 with a kitchen. Place and draw the play.',
      tpl_p_saque: 'Serve & net', tpl_p_saque_d: 'Serve and take the net to finish at the volley.',
      tpl_p_bandeja: 'Bandeja', tpl_p_bandeja_d: 'Answer the lob with a bandeja and hold the net.',
      tpl_p_globo: 'Lob & attack', tpl_p_globo_d: 'Deep lob, move up to the net and smash.',
      tpl_serve_volley: 'Serve & volley', tpl_serve_volley_d: 'Wide serve + rush to finish at the net.',
      tpl_return: 'Aggressive return', tpl_return_d: 'Deep return and take control.',
      tpl_baseline: 'Baseline rally', tpl_baseline_d: 'Cross-court exchange and change of direction.',
      tpl_drop: 'Drop & passing', tpl_drop_d: 'Drop shot to draw them in, then a passing shot.',
      tpl_counter: 'Counterattack', tpl_counter_d: 'Defend deep then turn to attack.',
      tpl_defense: 'Defense & lob', tpl_defense_d: 'Defensive return and a lob to reset.',
      use_template: 'Use template',
      // onboarding
      ob_title: 'Welcome to CourtLab', ob_sub: 'Your tennis tactics board in 3 steps.',
      ob_1_t: 'Draw the point', ob_1_d: 'In guided mode the app asks for each shot. Just tap where the ball goes.',
      ob_2_t: 'Animate the play', ob_2_d: 'Hit play and watch the point with realistic motion.',
      ob_3_t: 'Save & share', ob_3_d: 'Organize in folders, link rivals and export to image, PDF or video.',
      ob_start: 'Create my first tactic', ob_skip: 'Explore on my own',
      // editor extras
      duplicate_step: 'Duplicate step', tactic_duplicated: 'Tactic duplicated', dup_tactic: 'Duplicate tactic',
      shortcuts: 'Keyboard shortcuts', sc_play: 'Play / pause', sc_steps: 'Previous / next step',
      sc_undo: 'Undo last shot', sc_back: 'Back to home', sc_save: 'Save', kb_hint: 'Press ? for shortcuts',
      // tags
      f_tag: 'Tag', tag_off: 'No tag', tags_label: 'Tags', filter_tag: 'Tag',
      tag_serve: 'Serve', tag_return: 'Return', tag_defense: 'Defense', tag_attack: 'Attack', tag_special: 'Special',
      // score situation
      f_score: 'Score situation', score_any: 'Any', score_break: 'Break point', score_set: 'Set point',
      score_match: 'Match point', score_deuce: 'Deuce', score_pressure: 'Under pressure',
      // notes per shot
      step_note: 'Shot note', note_ph: 'e.g. open with slice to the backhand', notes_short: 'Note',
      // mirror
      mirror: 'Flip', flipped: 'Play flipped', mirror_d: 'Switch sides (deuce ↔ ad)',
      // doubles
      doubles: 'Doubles', singles: 'Singles', mode_play: 'Format', partner_you: 'Partner', partner_rival: 'Rival 2',
      // stats by surface / tactic
      stat_by_surface: 'By surface', stat_by_tactic: 'Tactics that work', stat_uses: 'uses', stat_record: 'record',
      stat_no_data: 'Play matches to see stats.', stat_success: 'success',
      // progress
      progress: 'Progress', progress_k: 'Recent matches', win_label: 'W', loss_label: 'L',
      // compare rivals
      compare: 'Compare', compare_title: 'Compare rivals', pick_two: 'Pick two rivals to compare.', vs: 'vs',
      // playbook
      playbook: 'Playbook PDF', playbook_d: 'Bundle several tactics into one printable document.',
      proplays: 'Pro plays', proplays_d: 'Ready-made coach-grade plays, free and premium.',
      playbook_title: 'Create Playbook', pick_for_playbook: 'Pick the tactics to include', export_playbook: 'Generate Playbook', playbook_empty: 'Select at least one tactic.',
      // sound + logo
      s_sound: 'Hit sound', s_haptic: 'Haptics', s_haptic_d: 'Tactile feedback when saving, completing and navigating.', s_logo: 'Club logo', s_logo_d: 'Shown on exported images and PDFs.',
      s_motion: 'Reduce animations', s_motion_d: 'Less motion across the app. Defaults to your system setting.',
      logo_added: 'Logo added', remove_logo: 'Remove logo', add_logo: 'Upload logo',
      settings: 'Settings', s_theme: 'Theme', theme_dark: 'Dark', theme_light: 'Light', s_accent: 'Accent color',
      s_account: 'Account', s_premium: 'Premium', go_premium: 'Go Premium', premium_on: 'Premium active', s_admin: 'Admin code', admin_ph: 'Administrator code', admin_ok: 'Admin account activated', admin_bad: 'Invalid code', admin_active: 'Admin · Free premium',
      s_about: 'About', s_version: 'Version', s_reset_tutorial: 'Replay tutorial', s_reset_tutorial_d: 'Show the welcome guide again', tutorial_reset: 'Tutorial reset · back to home', s_update: 'Check for updates', s_update_d: 'Reload the latest version of the app', updating: 'Updating…',
      s_support: 'Support', s_contact: 'Contact', s_feedback: 'Send feedback', feedback_ph: 'Tell us what to improve…', feedback_sent: 'Thanks for your feedback!', s_privacy: 'Privacy', s_terms: 'Terms', s_about: 'About',
      cloud_off: 'Cloud unavailable offline', sign_in: 'Sign in', sign_up: 'Sign up', create_account: 'Create account', sign_out: 'Sign out', signed_out: 'Signed out', synced_ok: 'Data synced', need_account: 'Create new account', have_account: 'I have an account', email: 'Email', password: 'Password', logged_as: 'Signed in', cloud_sync: 'Synced to cloud', forgot_pass: 'Forgot your password?', reset_title: 'Reset password', reset_send: 'Send link', reset_sent: "We've emailed you a link to reset your password.", reset_email_first: 'Enter your email first.', new_pass: 'New password', save_pass: 'Save password', pass_updated: 'Password updated · signed in', share_public: 'Create public link', share_public_d: 'Anyone with the link can view it', share_need_login: 'Sign in to create a public link', publishing: 'Publishing…', link_public: 'Public link', share_ready: 'Public link ready!', share_not_found: 'Link not found or expired',
      tactic_limit_hit: 'Free limit reached · go Premium for unlimited tactics',
      ref_welcome_toast: 'Invited by a friend · 7 days of Premium free! 🎁',
      ref_welcome_sub: 'Every friend who joins from your link gets 7 days of Premium free',
      install_app: 'Install app', install_d: 'Add it to your home screen', install_done: 'App installed! 🎾',
      trial_remind5: '2 days left of your Premium trial · cancel anytime', trial_remind_last: 'Last day of your Premium trial · keep it?',
      streak_days: 'days in a row', streak_day1: 'day', streak_today: 'on a roll today!', streak_label: 'Streak',
      notify_match: 'Match soon', notify_match_body: 'prep your plan on CourtLab', notify_remind: 'Remind me', notify_on: "We'll remind you before the match 🔔", notify_blocked: 'Enable notifications in your browser',
      save_label: 'Save', per_month_eq: '/mo',
      s_club: 'Club mode', club_title: 'Club', club_open: 'Open Club', club_d: 'Share tactics with your team',
      club_create: 'Create club', club_join: 'Join a club', club_name_ph: 'Club name', club_code_ph: 'Invite code',
      club_code: 'Code', club_created: 'Club created', club_joined: 'Joined the club', club_not_found: 'Invalid code',
      club_role_coach: 'Coach', club_role_player: 'Player', club_shared: 'Club tactics', club_share_tactic: 'Share tactic',
      club_players: 'Players', club_leave: 'Leave club', club_leave_confirm: 'Are you sure you want to leave the club?', club_left: 'You left the club',
      club_no_tactics: 'No shared tactics yet.', club_import: 'Add to mine', club_imported: 'Added to your library',
      club_shared_ok: 'Tactic shared with the club', club_need_login: 'Sign in to use Club mode',
      nav_home: 'Home', nav_tactics: 'Tactics', nav_rivals: 'Rivals', nav_matches: 'Matches', nav_profile: 'Profile',
      dash_hi: 'Your tactics board', dash_recent: 'Latest tactics', see_all_t: 'See all', quick_actions: 'Quick actions',
      fav: 'Favorite', favs_only: 'Favorites', view_toggle: 'List / grid view', fav_added: 'Added to favorites', fav_removed: 'Removed from favorites', all: 'All', r_partner: 'Partner (padel)', r_partner_ph: "Rival's partner",
      rank_title: 'Your rank', rank_next: 'to reach', rank_max: 'Max rank!', rank_xp: 'XP', r_debut: 'Rookie', r_pelot: 'Rallyer', r_estr: 'Strategist', r_maestro: 'Court Master', r_crack: 'Ace', r_leyenda: 'Legend',
      ach_first_tactic:'First shot', ach_first_tactic_d:'Create your first tactic',
      ach_five_tactics:'Strategist', ach_five_tactics_d:'Save 5 tactics',
      ach_first_padel:'Welcome to padel', ach_first_padel_d:'Create your first padel tactic',
      ach_first_match:'Game on', ach_first_match_d:'Log your first match',
      ach_ten_matches:'Veteran', ach_ten_matches_d:'Log 10 matches',
      ach_five_wins:'Winner', ach_five_wins_d:'Get 5 wins',
      ach_three_rivals:'Scout', ach_three_rivals_d:'Add 3 rivals',
      ach_streak3:'On a roll', ach_streak3_d:'Use it 3 days in a row',
      ach_streak7:'Unstoppable', ach_streak7_d:'Use it 7 days in a row',
      ach_share5:'Ambassador', ach_share5_d:'Share 5 tactics',
      ach_invite10:'Mentor', ach_invite10_d:'Invite 10 friends',
      rematch: 'Rematch', rematch_done: 'Rematch created', present: 'Present', present_mode: 'Presentation mode',
      export_scout_pdf: 'Scouting PDF', scout_report: 'Scouting report',
      // calendar / diary / goals
      qr_cal_s: 'Upcoming matches', qr_goal_s: 'Season targets', qr_diary_s: 'Notes & feelings',
      calendar: 'Calendar', cal_upcoming: 'Upcoming matches', cal_this_week: 'This week', cal_later: 'Later', cal_past: 'Played', cal_empty: 'No matches scheduled.',
      diary: 'Diary', diary_k: 'Training', new_entry: 'New entry', edit_entry: 'Edit entry', diary_empty_h: 'Your diary is empty', diary_empty_p: 'Log what you trained and how you felt, day by day.',
      d_date: 'Date', d_focus: 'What I trained', d_focus_ph: 'e.g. serve & volley, cross-court forehand', d_notes: 'Feelings / notes', d_notes_ph: 'How you felt, what to improve…', d_mood: 'Feel', d_dur: 'Duration', save_entry: 'Save entry', del_entry: 'Delete this entry?', entry_saved: 'Entry saved',
      mood_bad: 'Poor', mood_ok: 'OK', mood_good: 'Good', mood_great: 'Great',
      goals: 'Goals', goals_k: 'Season', new_goal: 'New goal', edit_goal: 'Edit goal', goals_empty_h: 'No goals yet', goals_empty_p: 'Set season goals and track your progress automatically.',
      g_title: 'Goal', g_title_ph: 'e.g. Win 70% on clay', g_type: 'Type', g_surface: 'Surface', g_any_surface: 'All', g_target: 'Target',
      gt_winrate: 'Win %', gt_wins: 'Number of wins', gt_matches: 'Matches played', gt_manual: 'Manual (I update it)', g_current: 'Current progress', save_goal: 'Save goal', del_goal: 'Delete this goal?', goal_saved: 'Goal saved', goal_done: 'Achieved!',
      s_lang: 'Language', s_data: 'Your data',
      s_export: 'Download backup', s_export_d: 'Tactics, folders, rivals and matches in one file.',
      s_import: 'Restore backup', s_import_d: 'Load a previous backup file.',
      s_wipe: 'Delete all data', s_wipe_confirm: 'Sure? Tactics, folders, rivals and matches in this browser will be erased.',
      data_exported: 'Backup downloaded', data_imported: 'Backup restored', import_bad: 'Invalid file',
      step_names: ['Wide serve','Cross-court return','Forehand to backhand','Net rush','Point finish'],
    },
  };

  TL.i18n = {
    lang: localStorage.getItem('tl_lang') || 'es',
    t(key) { return (DICT[this.lang] && DICT[this.lang][key]) ?? (DICT.es[key] ?? key); },
    set(lang) { this.lang = lang; localStorage.setItem('tl_lang', lang); },
    // "1 paso" / "3 pasos" — correct singular/plural in both languages
    steps(n) { const en = this.lang === 'en'; return n + ' ' + (n === 1 ? (en ? 'step' : 'paso') : (en ? 'steps' : 'pasos')); },
  };
})(window.TL = window.TL || {});
